name: sws_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fpdart: ^1.1.0
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
